on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure environment
      - run: |
          echo CONFIG_ID=$CONFIG_ID >> .env
          echo CONFIG_SECRET=$CONFIG_SECRET >> .env

      - name: Run the script
        run: |
          chmod +x ./script.sh
          ./script.sh
