on:
  push:
    branches:
      - main
      
# Job: connect to ubuntu VPS and run commands
# 1. Connect to VPS
# 2. workdir is /var/www/ensargok.net/app/
# 3. open python venv at /var/www/ensargok.net/venv/
# 4. install requirements.txt
# 5. run python main.py
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/ensargok.net/app/
            source /var/www/ensargok.net/venv/bin/activate
            pip install -r requirements.txt
            python main.py
