name: Test
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure environment
        run: echo AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} >> .env

      - name: Run the script
        run: |
          chmod +x ./script.sh
          ./script.sh
