name: Upload Videos
on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure environment
        run: |
          echo AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} >> .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} >> .env

      - name: Run the script
        run: |
          chmod +x ./script.sh
          ./script.sh

